#!/bin/sh
#!/usr/bin/env ruby
cd /home/ubuntu/crawler
echo 'wtf'
echo 'wtf'
echo 'wtf'
echo 'wtf'
echo 'wtf'
echo 'wtf'
source /home/ubuntu/crawler/.crawl_bot.env
exec /home/ubuntu/.rbenv/shims/ruby crawl_bot.rb
exit 0
